language: node_js
node_js:
  - "node"
before_script:
  - "npm install -g gitbook-cli"
script:
  - "gitbook install && gitbook build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _book
  fqdn: guide.openmrs.org
  name: "Burke Mamlin"
  email: "burke@openmrs.org"
